import React, { useState, useEffect } from 'react';
import { 
  ArrowLeft, 
  CheckCircle, 
  Camera, 
  Minus, 
  Plus, 
  Printer, 
  Save, 
  Lock, 
  Building2, 
  Truck,
  Edit2,
  Check
} from 'lucide-react';
import { Animal, AnimalSpecies } from '../../types';

interface ViewAddAnimalProps {
  existingAnimals: Animal[];
  onBack: () => void;
  onSave: (animal: Animal, printImmediate: boolean) => void;
}

export const ViewAddAnimal: React.FC<ViewAddAnimalProps> = ({ 
  existingAnimals, 
  onBack, 
  onSave 
}) => {
  const [species, setSpecies] = useState<AnimalSpecies>('sapi');
  const [customEartag, setCustomEartag] = useState('');
  const [isManualEartag, setIsManualEartag] = useState(false);
  const [breed, setBreed] = useState('Limousin');
  const [sex, setSex] = useState<'Jantan' | 'Betina'>('Jantan');
  const [origin, setOrigin] = useState<'Lahir di Farm' | 'Beli dari Luar'>('Lahir di Farm');
  const [motherTag, setMotherTag] = useState('');
  const [fatherTag, setFatherTag] = useState('');
  const [birthDate, setBirthDate] = useState(() => new Date().toISOString().split('T')[0]);
  const [kandang, setKandang] = useState('Kandang A1 (Penggemukan Sapi)');
  const [weight, setWeight] = useState(380);
  const [targetWeight, setTargetWeight] = useState(550);
  const [notes, setNotes] = useState('');
  const [photoUrl, setPhotoUrl] = useState('');
  const [photoUploaded, setPhotoUploaded] = useState(false);

  const breedOptions: Record<AnimalSpecies, string[]> = {
    sapi: ['Limousin', 'Simental', 'Brahman', 'Peranakan Ongole (PO)', 'Angus', 'FH (Friesian Holstein)'],
    kambing: ['Boer', 'Jawa Randu', 'Etawa (PE)', 'Saanen', 'Kacang'],
    domba: ['Garut', 'Dorper', 'Merino', 'Compass Agrinak', 'Ekor Gemuk'],
    kerbau: ['Kerbau Lumpur', 'Kerbau Murrah', 'Kerbau Toraja']
  };

  // Generate automatic eartag code based on current year & existing count
  const speciesPrefix = species === 'sapi' ? 'SP' : species === 'kambing' ? 'KB' : species === 'domba' ? 'DB' : 'KR';
  const year2Digit = new Date().getFullYear().toString().slice(-2);
  const countSpecies = existingAnimals.filter(a => a.species === species).length + 1;
  const autoGeneratedCode = `${speciesPrefix}-${year2Digit}-${String(countSpecies).padStart(4, '0')}`;

  const currentEartag = isManualEartag && customEartag.trim() ? customEartag.trim().toUpperCase() : autoGeneratedCode;

  const handleSpeciesChange = (newSpecies: AnimalSpecies) => {
    setSpecies(newSpecies);
    setBreed(breedOptions[newSpecies][0]);
    if (newSpecies === 'sapi') {
      setKandang('Kandang A1 (Penggemukan Sapi)');
      setWeight(380);
      setTargetWeight(550);
    } else if (newSpecies === 'kambing') {
      setKandang('Kandang B (Penggemukan Kambing)');
      setWeight(35);
      setTargetWeight(55);
    } else if (newSpecies === 'domba') {
      setKandang('Kandang C (Penggemukan Domba)');
      setWeight(30);
      setTargetWeight(45);
    } else {
      setKandang('Kandang D (Kerbau)');
      setWeight(420);
      setTargetWeight(600);
    }
  };

  const handlePhotoClick = () => {
    // Toggle simulated photo
    if (!photoUploaded) {
      setPhotoUploaded(true);
      const defaultPhotos: Record<AnimalSpecies, string> = {
        sapi: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?auto=format&fit=crop&w=800&q=80',
        kambing: 'https://images.unsplash.com/photo-1524024973431-2ad916746881?auto=format&fit=crop&w=800&q=80',
        domba: 'https://images.unsplash.com/photo-1484557052118-f32bd25b45b5?auto=format&fit=crop&w=800&q=80',
        kerbau: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?auto=format&fit=crop&w=800&q=80',
      };
      setPhotoUrl(defaultPhotos[species]);
    } else {
      setPhotoUploaded(false);
      setPhotoUrl('');
    }
  };

  const handleSubmit = (printImmediate: boolean) => {
    if (!currentEartag) {
      alert('Nomor Eartag tidak boleh kosong.');
      return;
    }

    // Check duplicate eartag
    if (existingAnimals.some(a => a.eartag.toLowerCase() === currentEartag.toLowerCase())) {
      alert(`Nomor Eartag ${currentEartag} sudah terdaftar! Harap gunakan nomor lain.`);
      return;
    }

    const newAnimal: Animal = {
      id: `animal-${Date.now()}`,
      eartag: currentEartag,
      species,
      breed,
      sex,
      age: 'Baru Masuk',
      kandang,
      origin,
      weight: Number(weight),
      initialWeight: Number(weight),
      targetWeight: Number(targetWeight),
      adg: 0.80,
      status: 'aktif',
      statusBadge: 'AKTIF • SEHAT',
      statusColor: 'green',
      birthDate,
      motherTag: motherTag || undefined,
      fatherTag: fatherTag || undefined,
      notes: notes || undefined,
      photoUrl: photoUrl || undefined,
      rfid: `RFID-${Date.now().toString().slice(-10)}`
    };

    onSave(newAnimal, printImmediate);
  };

  return (
    <div className="space-y-6 pb-24 md:pb-10 max-w-xl mx-auto">
      {/* Top Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <button
            onClick={onBack}
            className="w-9 h-9 rounded-xl bg-gray-100 hover:bg-gray-200 flex items-center justify-center text-gray-700 transition"
          >
            <ArrowLeft size={18} />
          </button>
          <div>
            <h1 className="text-xl font-bold text-gray-900">Tambah Ternak Baru</h1>
            <p className="text-xs text-gray-500">Input identitas, asal, dan data fisik ternak</p>
          </div>
        </div>

        <div className="bg-[#E6F4EA] text-[#1E7E34] text-[11px] font-bold px-2.5 py-1 rounded-full flex items-center gap-1.5 shrink-0">
          <span className="w-1.5 h-1.5 rounded-full bg-[#1E7E34]"></span>
          SHIFT AKTIF
        </div>
      </div>

      {/* Auto-Generated / Custom Eartag Card */}
      <div className="bg-[#1E4D2B] text-white rounded-2xl p-4 sm:p-5 shadow-sm space-y-2">
        <div className="flex items-center justify-between text-xs">
          <span className="font-semibold text-emerald-200 uppercase tracking-wider flex items-center gap-1.5">
            FORMAT BARCODE TERSTANDAR
          </span>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => setIsManualEartag(!isManualEartag)}
              className="text-[11px] bg-white/20 hover:bg-white/30 text-white px-2 py-0.5 rounded flex items-center gap-1 transition"
            >
              <Edit2 size={11} /> {isManualEartag ? 'Gunakan Auto' : 'Kustom ID'}
            </button>
            <span className="bg-black/25 text-[#A3E635] text-[10px] font-black px-2 py-0.5 rounded tracking-wider">
              ANTI-DUPLIKAT
            </span>
          </div>
        </div>

        <div>
          <p className="text-[11px] text-emerald-200/90 font-medium">
            {isManualEartag ? 'Nomor Eartag Kustom Manual' : 'Nomor Eartag Resmi Terkunci'}
          </p>
          <div className="flex items-center justify-between mt-1">
            {isManualEartag ? (
              <input
                type="text"
                value={customEartag}
                onChange={(e) => setCustomEartag(e.target.value.toUpperCase())}
                placeholder={autoGeneratedCode}
                className="font-mono text-2xl sm:text-3xl font-black bg-white/10 border border-white/30 rounded-xl px-3 py-1 text-white focus:outline-none w-full max-w-[280px]"
              />
            ) : (
              <span className="font-mono text-3xl sm:text-4xl font-black tracking-tight text-white">
                {currentEartag}
              </span>
            )}
            <div className="w-8 h-8 rounded-full bg-white/10 flex items-center justify-center text-[#A3E635] shrink-0 ml-2">
              <CheckCircle size={20} />
            </div>
          </div>
        </div>

        <div className="pt-2 border-t border-white/15 flex items-center gap-1.5 text-[11px] text-emerald-200/80">
          <Lock size={12} className="shrink-0" />
          <span>
            Format: [Kode Spesies]-[2 Digit Tahun]-[Nomor Urut 4 Digit].
          </span>
        </div>
      </div>

      {/* Section 1: Spesies & Karakteristik */}
      <div className="space-y-4 bg-white p-5 rounded-2xl border border-gray-200/80 shadow-xs">
        <h3 className="text-xs font-black text-gray-800 uppercase tracking-wider flex items-center gap-2">
          <span className="w-2 h-4 bg-[#27532B] rounded-sm"></span>
          1. Spesies & Karakteristik
        </h3>

        {/* Species selector */}
        <div>
          <label className="block text-xs font-bold text-gray-700 mb-2">
            Pilih Spesies Ternak *
          </label>
          <div className="grid grid-cols-2 gap-2.5">
            {[
              { id: 'sapi', label: 'Sapi', code: 'SP', icon: '🐄' },
              { id: 'kambing', label: 'Kambing', code: 'KB', icon: '🐐' },
              { id: 'domba', label: 'Domba', code: 'DB', icon: '🐑' },
              { id: 'kerbau', label: 'Kerbau', code: 'KR', icon: '🐃' },
            ].map((sp) => (
              <button
                key={sp.id}
                type="button"
                onClick={() => handleSpeciesChange(sp.id as AnimalSpecies)}
                className={`p-3 rounded-xl border flex items-center justify-between transition ${
                  species === sp.id
                    ? 'bg-[#1E4D2B] text-white border-[#1E4D2B]'
                    : 'bg-gray-50 hover:bg-gray-100 text-gray-800 border-gray-200'
                }`}
              >
                <div className="flex items-center gap-2 text-sm font-bold">
                  <span>{sp.icon}</span>
                  <span>{sp.label}</span>
                </div>
                <span className={`text-[10px] font-mono px-1.5 py-0.5 rounded ${
                  species === sp.id ? 'bg-white/20 text-white' : 'bg-gray-200 text-gray-600'
                }`}>
                  {sp.code}
                </span>
              </button>
            ))}
          </div>
        </div>

        {/* Ras / Bangsa */}
        <div>
          <label className="block text-xs font-bold text-gray-700 mb-1.5">
            Ras / Bangsa Ternak *
          </label>
          <select
            value={breed}
            onChange={(e) => setBreed(e.target.value)}
            className="w-full bg-gray-50 border border-gray-300 rounded-xl px-3.5 py-2.5 text-sm font-medium text-gray-900 focus:outline-none focus:ring-2 focus:ring-[#27532B]/20 focus:border-[#27532B]"
          >
            {breedOptions[species].map((b) => (
              <option key={b} value={b}>{b}</option>
            ))}
          </select>
        </div>

        {/* Jenis Kelamin */}
        <div>
          <label className="block text-xs font-bold text-gray-700 mb-1.5">
            Jenis Kelamin *
          </label>
          <div className="grid grid-cols-2 gap-2.5">
            <button
              type="button"
              onClick={() => setSex('Jantan')}
              className={`py-2.5 px-3 rounded-xl border text-xs font-bold flex items-center justify-center gap-2 transition ${
                sex === 'Jantan'
                  ? 'bg-[#1E4D2B] text-white border-[#1E4D2B]'
                  : 'bg-gray-50 text-gray-700 border-gray-200 hover:bg-gray-100'
              }`}
            >
              ♂ Jantan
            </button>
            <button
              type="button"
              onClick={() => setSex('Betina')}
              className={`py-2.5 px-3 rounded-xl border text-xs font-bold flex items-center justify-center gap-2 transition ${
                sex === 'Betina'
                  ? 'bg-[#1E4D2B] text-white border-[#1E4D2B]'
                  : 'bg-gray-50 text-gray-700 border-gray-200 hover:bg-gray-100'
              }`}
            >
              ♀ Betina
            </button>
          </div>
        </div>
      </div>

      {/* Section 2: Asal Usul & Silsilah */}
      <div className="space-y-4 bg-white p-5 rounded-2xl border border-gray-200/80 shadow-xs">
        <h3 className="text-xs font-black text-gray-800 uppercase tracking-wider flex items-center gap-2">
          <span className="w-2 h-4 bg-[#27532B] rounded-sm"></span>
          2. Asal Usul & Silsilah
        </h3>

        <div>
          <label className="block text-xs font-bold text-gray-700 mb-1.5">
            Asal Ternak *
          </label>
          <div className="grid grid-cols-2 gap-2.5">
            <button
              type="button"
              onClick={() => setOrigin('Lahir di Farm')}
              className={`py-2.5 px-3 rounded-xl border text-xs font-bold flex items-center justify-center gap-2 transition ${
                origin === 'Lahir di Farm'
                  ? 'bg-[#1E4D2B] text-white border-[#1E4D2B]'
                  : 'bg-gray-50 text-gray-700 border-gray-200 hover:bg-gray-100'
              }`}
            >
              <Building2 size={15} /> Lahir di Farm
            </button>
            <button
              type="button"
              onClick={() => setOrigin('Beli dari Luar')}
              className={`py-2.5 px-3 rounded-xl border text-xs font-bold flex items-center justify-center gap-2 transition ${
                origin === 'Beli dari Luar'
                  ? 'bg-[#1E4D2B] text-white border-[#1E4D2B]'
                  : 'bg-gray-50 text-gray-700 border-gray-200 hover:bg-gray-100'
              }`}
            >
              <Truck size={15} /> Beli dari Luar
            </button>
          </div>
        </div>

        <div>
          <div className="flex justify-between items-center mb-1">
            <label className="text-xs font-bold text-gray-700">Induk Betina</label>
            <span className="text-[11px] text-gray-400">Opsional</span>
          </div>
          <select
            value={motherTag}
            onChange={(e) => setMotherTag(e.target.value)}
            className="w-full bg-gray-50 border border-gray-300 rounded-xl px-3.5 py-2.5 text-xs text-gray-700 focus:outline-none"
          >
            <option value="">-- Pilih Induk Betina Aktif --</option>
            {existingAnimals.filter(a => a.sex === 'Betina').map(a => (
              <option key={a.id} value={a.eartag}>{a.eartag} ({a.species} {a.breed})</option>
            ))}
          </select>
        </div>

        <div>
          <div className="flex justify-between items-center mb-1">
            <label className="text-xs font-bold text-gray-700">Pejantan / Kode Semen IB</label>
            <span className="text-[11px] text-gray-400">Opsional</span>
          </div>
          <select
            value={fatherTag}
            onChange={(e) => setFatherTag(e.target.value)}
            className="w-full bg-gray-50 border border-gray-300 rounded-xl px-3.5 py-2.5 text-xs text-gray-700 focus:outline-none"
          >
            <option value="">-- Pilih Pejantan Aktif / Semen IB --</option>
            {existingAnimals.filter(a => a.sex === 'Jantan').map(a => (
              <option key={a.id} value={a.eartag}>{a.eartag} ({a.species} {a.breed})</option>
            ))}
            <option value="IB-SIM-9921">IB-SIM-9921 (Semen Simental Impor BIB Lembang)</option>
          </select>
        </div>
      </div>

      {/* Section 3: Tanggal & Lokasi */}
      <div className="space-y-4 bg-white p-5 rounded-2xl border border-gray-200/80 shadow-xs">
        <h3 className="text-xs font-black text-gray-800 uppercase tracking-wider flex items-center gap-2">
          <span className="w-2 h-4 bg-[#27532B] rounded-sm"></span>
          3. Tanggal & Lokasi
        </h3>

        <div>
          <label className="block text-xs font-bold text-gray-700 mb-1.5">
            Tanggal Masuk / Lahir *
          </label>
          <input
            type="date"
            value={birthDate}
            onChange={(e) => setBirthDate(e.target.value)}
            className="w-full bg-gray-50 border border-gray-300 rounded-xl px-3.5 py-2.5 text-sm text-gray-900 focus:outline-none"
          />
        </div>

        <div>
          <label className="block text-xs font-bold text-gray-700 mb-1.5">
            Penempatan Kandang *
          </label>
          <input
            type="text"
            value={kandang}
            onChange={(e) => setKandang(e.target.value)}
            placeholder="Contoh: Kandang A1 (Penggemukan Sapi)"
            className="w-full bg-gray-50 border border-gray-300 rounded-xl px-3.5 py-2.5 text-sm text-gray-900 focus:outline-none"
          />
        </div>
      </div>

      {/* Section 4: Data Fisik & Foto */}
      <div className="space-y-4 bg-white p-5 rounded-2xl border border-gray-200/80 shadow-xs">
        <h3 className="text-xs font-black text-gray-800 uppercase tracking-wider flex items-center gap-2">
          <span className="w-2 h-4 bg-[#27532B] rounded-sm"></span>
          4. Data Fisik & Foto
        </h3>

        {/* Stepper Bobot Masuk */}
        <div>
          <label className="block text-xs font-bold text-gray-700 mb-2">
            Bobot Masuk (Kilogram) *
          </label>
          <div className="bg-gray-100 rounded-2xl p-2.5 flex items-center justify-between">
            <button
              type="button"
              onClick={() => setWeight((w) => Math.max(5, w - (species === 'sapi' ? 5 : 1)))}
              className="w-12 h-12 bg-white hover:bg-gray-200 rounded-xl flex items-center justify-center text-gray-800 font-black shadow-xs transition"
            >
              <Minus size={20} />
            </button>

            <div className="text-center">
              <input
                type="number"
                value={weight}
                onChange={(e) => setWeight(Number(e.target.value))}
                className="w-24 text-center text-3xl font-black text-gray-900 bg-transparent focus:outline-none"
              />
              <span className="text-sm font-semibold text-gray-500 ml-1">kg</span>
            </div>

            <button
              type="button"
              onClick={() => setWeight((w) => w + (species === 'sapi' ? 5 : 1))}
              className="w-12 h-12 bg-white hover:bg-gray-200 rounded-xl flex items-center justify-center text-gray-800 font-black shadow-xs transition"
            >
              <Plus size={20} />
            </button>
          </div>
        </div>

        {/* Target Bobot */}
        <div>
          <label className="block text-xs font-bold text-gray-700 mb-1">
            Target Bobot Panen / Jual (kg)
          </label>
          <input
            type="number"
            value={targetWeight}
            onChange={(e) => setTargetWeight(Number(e.target.value))}
            className="w-full bg-gray-50 border border-gray-300 rounded-xl px-3.5 py-2 text-sm text-gray-900 focus:outline-none"
          />
        </div>

        {/* Foto Upload Trigger */}
        <div>
          <label className="block text-xs font-bold text-gray-700 mb-1.5">
            Foto Utama Ternak & Eartag Terpasang
          </label>
          <div
            onClick={handlePhotoClick}
            className={`border-2 border-dashed rounded-2xl p-5 text-center cursor-pointer transition ${
              photoUploaded 
                ? 'border-emerald-500 bg-emerald-50/50' 
                : 'border-gray-300 hover:border-[#1E4D2B] bg-gray-50'
            }`}
          >
            {photoUploaded && photoUrl ? (
              <div className="space-y-2">
                <img src={photoUrl} alt="Preview" className="w-24 h-24 object-cover mx-auto rounded-xl shadow-xs" />
                <p className="text-xs font-bold text-emerald-800">✓ Foto Ternak Siap Digunakan (Klik untuk Ganti)</p>
              </div>
            ) : (
              <>
                <div className="w-11 h-11 rounded-xl bg-white border border-gray-200 mx-auto flex items-center justify-center text-gray-600 mb-2 shadow-xs">
                  <Camera size={20} />
                </div>
                <p className="text-xs font-bold text-gray-800">
                  Ketuk untuk Pasang Foto / Sampel
                </p>
                <p className="text-[11px] text-gray-500 mt-0.5">
                  Foto telinga eartag dan kondisi fisik
                </p>
              </>
            )}
          </div>
        </div>

        {/* Catatan Khusus */}
        <div>
          <div className="flex justify-between items-center mb-1">
            <label className="text-xs font-bold text-gray-700">Catatan Ciri Khusus / Kesehatan</label>
            <span className="text-[11px] text-gray-400">Opsional</span>
          </div>
          <textarea
            rows={2}
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Contoh: Bercak putih di dahi, vaksinasi tahap 1 selesai di kandang karantina."
            className="w-full bg-gray-50 border border-gray-300 rounded-xl p-3 text-xs text-gray-900 focus:outline-none"
          ></textarea>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="space-y-2.5">
        <button
          type="button"
          onClick={() => handleSubmit(true)}
          className="w-full bg-[#27532B] hover:bg-[#1E4122] text-white py-3.5 px-4 rounded-xl text-xs sm:text-sm font-bold flex items-center justify-center gap-2 transition shadow-sm active:scale-98"
        >
          <Printer size={16} />
          SIMPAN & CETAK LABEL EARTAG
        </button>

        <button
          type="button"
          onClick={() => handleSubmit(false)}
          className="w-full bg-gray-200 hover:bg-gray-300 text-gray-800 py-3.5 px-4 rounded-xl text-xs sm:text-sm font-bold flex items-center justify-center gap-2 transition"
        >
          <Save size={16} />
          SIMPAN SAJA
        </button>
      </div>
    </div>
  );
};
